-- Create a test database

create database example_db;

-- Create Schema ODS, Staging and DataWareHouse
create schema  Staging;
create schema ODS;
create schema DataWareHouse;

drop database test;

--- Loading data from 9 tables into staging along with the SQL

CREATE STAGE "EXAMPLE_DB"."STAGING".Employees;
CREATE STAGE "EXAMPLE_DB"."STAGING".Facilities;
CREATE STAGE "EXAMPLE_DB"."STAGING".Floors;
CREATE STAGE "EXAMPLE_DB"."STAGING".Frequency;
CREATE STAGE "EXAMPLE_DB"."STAGING".HighTouchAreas;
CREATE STAGE "EXAMPLE_DB"."STAGING".Protocol;
CREATE STAGE "EXAMPLE_DB"."STAGING".Rooms;
CREATE STAGE "EXAMPLE_DB"."STAGING".Complex;
CREATE STAGE "EXAMPLE_DB"."STAGING".CleaningSchedule;

--- Creating tables for database 

-- Create Schedule
CREATE TABLE "EXAMPLE_DB"."STAGING"."CLEANING_SCHEDULE" 
("TRANSACTIONID" INTEGER, "STEPID" INTEGER, "CLEANED_ON" DATE, "FREQUENCYID" INTEGER, 
"BUILDINGID" INTEGER, "FLOORID" INTEGER, "ROOMID" INTEGER, "EMPLOYEEID" INTEGER, 
"SPOTID" INTEGER, "TEST_VALUE" INTEGER, "EFFICIENCY" INTEGER);

-- Create Complex Table

CREATE TABLE "EXAMPLE_DB"."STAGING"."COMPLEX" 
("ComplexID" INTEGER, "Complex" STRING);

-- Create Employee Table
CREATE TABLE "EXAMPLE_DB"."STAGING"."EMPLOYEE" 
("EmployeeID" INTEGER, "First Name" STRING,"Last Name" STRING,"Badge Status" STRING,"Remote/Office" STRING);

-- Create Building Table

CREATE TABLE "EXAMPLE_DB"."STAGING"."BUILDING" 
("BuildingID" INTEGER, "BuildingName" STRING,"SqFt" INTEGER,"ComplexID" INTEGER);

-- Create Floor Table

CREATE TABLE "EXAMPLE_DB"."STAGING"."FLOOR" 
("FloorID" INTEGER, "FloorName" STRING,"BuildingID" INTEGER);

-- Create Frequency Table
CREATE TABLE "EXAMPLE_DB"."STAGING"."FREQUENCY" 
("FrequencyID" INTEGER, "BuildingID" INTEGER,"Frequency" INTEGER);

-- Create HighTouchAreas Table
CREATE TABLE "EXAMPLE_DB"."STAGING"."HighTouchAreas" 
("SpotID" INTEGER, "HighTouchAreas" STRING);

-- Create Protocol Table
CREATE TABLE "EXAMPLE_DB"."STAGING"."PROTOCOL" 
("ProtocolID" INTEGER, "StepID" INTEGER,"StepName" STRING);

-- Create Room Table
CREATE TABLE "EXAMPLE_DB"."STAGING"."ROOM" 
("RoomID" INTEGER, "RoomName" STRING,"FloorID" INTEGER,"BuildingID" INTEGER,"Total Area" STRING,"Cleaned Area" STRING);


--- Create Load file formats

CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".Cleaning_Schedule_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".COMPLEX_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".EMPLOYEE_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".BUILDING_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".FLOOR_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".FREQUENCY_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".HighTouchAreas_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".PROTOCOL_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');
CREATE FILE FORMAT "EXAMPLE_DB"."STAGING".ROOM_CSV TYPE = 'CSV' COMPRESSION = 'AUTO' FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');





PUT file:///Users/arpitsharma/Desktop/ML/09_Udacity/06-Udacity_Data_Architect/DWH_Exercise/Cleaning_Testing Exercise Files/CleaningSchedule.csv @CLEANING_SCHEDULE/ui1623233800644
COPY INTO "EXAMPLE_DB"."STAGING"."CLEANING_SCHEDULE" FROM @/ui1623233800644 ON_ERROR = 'ABORT_STATEMENT' PURGE = TRUE;


